cmd_vel_mux:
  ros__parameters:
    subscribers:
        safe_reactive_controller:
          topic:       "cmd_vel_mux/safety_controller"
          timeout:     0.2
          priority:    10
          short_desc:  "Kobuki Safety Controller"
        navigation_stack:
          topic:       "cmd_vel_mux/nav2"
          timeout:     0.5
          priority:    1
          short_desc:  "Navigation stack controller or anything else"
        teleop:
          topic:       "cmd_vel_mux/teleop"
          timeout:     0.1
          priority:    5
          short_desc:  "Keyboard or joystick teleop"
    publisher:       "cmd_vel"