cmd_vel_mux:
  ros__parameters:
    subscribers:
      - name:        "Safe reactive controller"
        topic:       "cmd_vel_mux/safety_controller"
      timeout:        0.2
      priority:       10
      - name:        "Keyboard or joystick teleop"
        topic:       "cmd_vel_mux/teleop"
      timeout:        0.2
      priority:       5
      - name:        "Misc and Nav2"
        topic:       "cmd_vel"
      timeout:        0.2
      priority:       1

    publisher:    "output/cmd_vel"
